
server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.32.25
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
shika:
  jwt:
    pubKeyPath: C:\tmp\rsa\rsa.pub # 公钥地址
    cookieName: SK_TOKEN # cookie的名称
