server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shika2?serverTimezone=UTC
    username: root
    password:
  rabbitmq:
    host: 192.168.32.25
    username: jiang
    password: jiang
    virtual-host: /shika
  redis:
    host: 192.168.32.25
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: com.shika.user.pojo